<?php

define('TZUSER_OVERVIEW_YELLOW_LIMIT', 24*60*60);

function tzuser_menu() {
  $items['admin/user/tzuser/ajax/autocomplete/user'] = array(
    'page callback' => 'tzuser_ajax_autocomplete_user',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['tzuser'] = array(
    'title' => 'Employees',
    'access arguments' => array('view employees'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tzuser_user_overview'),
    'file' => 'includes/tzuser.overview.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['tzuser/overview'] = array(
    'title' => 'Employee overview',
    'access arguments' => array('view employees'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['tzuser/overview/ajax'] = array(
    'page callback' => 'tzuser_overview_ajax',
    'access arguments' => array('view employees'),
    'file' => 'includes/tzuser.overview.inc',
    'type' => MENU_CALLBACK,
  );
  $items['tzuser/add'] = array(
    'title' => 'Add employees',
    'access arguments' => array('manage employees'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tzuser_add_users_form'),
    'file' => 'includes/tzuser.add.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -9,
  );
  return $items;
}

function tzuser_perm() {
  return array('view employees', 'manage employees');
}

/**
 * Implementation of hook_theme().
 * Declares the theme function for formatting the add user form rows.
 */
function tzuser_theme() {
  return array(
    'tzuser_add_users_rows' => array(
      'arguments' => array('element' => NULL),
      'file' => 'includes/tzuser.theme.inc',
    ),
    'tzuser_user_overview' => array(
      'arguments' => array('form' => NULL),
      'file' => 'includes/tzuser.theme.inc',
    ),
    'traffic_light' => array(
      'arguments' => array('status' => NULL),
      'file' => 'includes/tzuser.theme.inc',
    ),
    'time_ago' => array(
      'arguments' => array('time' => NULL),
      'file' => 'includes/tzuser.theme.inc',
    ),
    'due_reports_count' => array(
      'arguments' => array('count' => NULL),
      'file' => 'includes/tzuser.theme.inc',
    ),
  );
}

function tzuser_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'tzuser') . '/includes',
  );
}

function tzuser_user($op, &$edit, &$account, $category = NULL) {
  switch($op) {
    case 'delete':
      db_query('DELETE FROM {tzuser} WHERE uid = %d', $account->uid);
      break;

    case 'insert':
      _tzuser_save_entry($edit, $account);
      break;

    case 'load':
      $account->tzuser = _tzuser_load_entry($account);
      break;

    case 'update':
      _tzuser_save_entry($edit, $account);
      break;

    case 'view':
      _tzuser_show_entry($account);
      break;

    case 'validate':
      _tzuser_validate_entry($edit);
      break;

    case 'form':
    case 'register':
      return _tzuser_user_form($account);
  }
}

/**
 * Implements hook_theme_registry_alter()
 *
 * Swap in our own replacement for theme_username().
 **/
function tzuser_theme_registry_alter(&$theme_registry) {
  if (!empty($theme_registry['form_element'])) {
    $path = drupal_get_path('module', 'tzuser');
    $theme_registry['username']['function'] = 'tzuser_username';
    $theme_registry['username']['file'] = $path . '/includes/tzuser.theme.inc';
    $theme_registry['username']['theme path'] = $path;
    $theme_registry['username']['theme paths'][0] = $path;
  }
}

function tzuser_form_alter(&$form, &$form_state, $form_id) {
  /* Hide e-mail field in the user registration and user edit forms,
   * since we don't really care about it and it is cumbersome to
   * have to enter it just to satisfy drupal.
   */
  if ($form_id == 'user_register' ||
      $form_id == 'user_profile_form') {
    $form['account']['mail']['#type'] = 'hidden';
    $form['account']['mail']['#value'] = _tzuser_generate_fake_email();
  }
}

/**
 * AJAX callback for autocompleting user names. Groked from user.module.
 * This code is hard to read, but the requirements for autocomplete
 * functions are poorly documented so I'm not sure about how to
 * rewrite it.
 */
function tzuser_ajax_autocomplete_user($string = '') {
  // The user enters a comma-separated list of tags. We only autocomplete the last tag.
  $array = drupal_explode_tags($string);

  // Fetch last tag
  $last_string = trim(array_pop($array));
  $matches = array();
  if ($last_string != '') {
    $prefix = count($array) ? implode(', ', $array) . ', ' : '';

    if (strpos('anonymous', strtolower($last_string)) !== FALSE) {
      $matches[$prefix . 'Anonymous'] = 'Anonymous';
    }
    $result = db_query_range("SELECT fullname FROM {tzuser} WHERE LOWER(fullname) LIKE LOWER('%s%%')", $last_string, 0, 10);

    while ($account = db_fetch_object($result)) {
      $n = $account->fullname;
      // Commas and quotes in terms are special cases, so encode 'em.
      if (strpos($account->fullname, ',') !== FALSE || strpos($account->fullname, '"') !== FALSE) {
        $n = '"' . str_replace('"', '""', $account->fullname) . '"';
      }
      $matches[$prefix . $n] = check_plain($account->fullname);
    }
  }

  drupal_json($matches);
}

/**
 * Add a new user
 * @param string $fullname Users full name
 * @param string $mobile_number Users mobile number
 * @param string $username Users username
 * @param string $password Users
 * @param Array $extra_data Extra fields to save in the user object
 * @return object Fully loaded user object on success, otherwise FALSE
 */
function tzuser_add_user($fullname, $username, $password = '', $mobile_number = '', $extra_data = array()) {
  if(empty($fullname) || empty($username)) {
    return FALSE;
  }

  // Try to load account
  $account = user_load(array('name' => $username));

  if(!is_array($extra_data)) {
    $extra_data = array();
  }
  $user_data = $extra_data;
  $user_data['status'] = 1;
  $user_data['tzuser'] = array(
    'fullname' => $fullname,
    'mobile' => tzuser_validate_phone_number($mobile_number),
  );

  if (!$account) {
    // New account
    if(empty($password)) {
      /* Generate a password if none is provided. This can be changed by the admin
       * or when the user is authenticated remotely for the first time.
       */
      $password = user_password(10);
    }
    $mail = _tzuser_generate_fake_email();
    $user_data['mail'] = $mail;
    $user_data['init'] = $mail;
    $user_data['name'] = $username;
    $user_data['pass'] = $password;
  }

  drupal_alter('tzuser_add_user_data', $user_data);

  $account = user_save($account, $user_data);
  if (!$account) {
    return FALSE;
  }

  return $account;
}

/**
 * Validate a mobile phone number and strip out all extra characters
 * @param string $number phone number to validate
 * @return all-numeric phone number if success, otherwise FALSE
 */
function tzuser_validate_phone_number($number) {
  // Remove characters like '+', '-', ' ' and '/'
  $mobile_number = preg_replace('/[\+\- \/]/', '', $number);
  // There should be only digits left now
  if(!ctype_digit($mobile_number) || strlen($mobile_number) < 6) {
    return FALSE;
  }
  return $mobile_number;
}

/**
 * @param array $account
 * @param int @now timestamp
 * @return TZUserStatus status
 */
function tzuser_get_user_status($account, $now) {
  tzbase_include_proto_classes();

  $status = new TZUserStatus($account->login, TZUSER_OVERVIEW_YELLOW_LIMIT);
  if($status->getStatusCode($now) == TZUserStatus::RED) {
    return $status;
  }

  $result = db_query('SELECT COUNT(n.vid) AS count, MIN(endtime) AS endtime FROM {node} n INNER JOIN {tzreport} tzr ON tzr.vid = n.vid WHERE flags != 255 AND assignedto = %d AND flags < %d AND endtime < %d', $account->uid, TZFlags::REPORTED, $now);
  $data = db_fetch_object($result);
  if($data) {
    $status->setNumberOfDueReports(intval($data->count));
    $status->setEarliestDueEndTime(intval($data->endtime));
  }

  return $status;
}


function _tzuser_load_entry($account) {
  $entry = array();

  $db_entry = db_fetch_array(db_query('SELECT * FROM {tzuser} WHERE uid = %d', $account->uid));
  if(is_array($db_entry)) {
    $entry = array_merge($entry, $db_entry);
    // unset uid since we don't need it in both $account->uid and $account->tzuser[uid]
    unset($entry['uid']);
  }

  return $entry;
}

function _tzuser_save_entry(&$edit, $account) {
  if (empty($edit['tzuser'])) {
    return;
  }

  $entry = array('uid' => $account->uid);
  if(!empty($account->tzuser)) {
    $entry = array_merge($entry, $account->tzuser);
  }
  $entry = array_merge($entry, $edit['tzuser']);

  if(empty($account->tzuser)) {
    drupal_write_record('tzuser', $entry);
  } else {
    drupal_write_record('tzuser', $entry, 'uid');
  }
  $edit['tzuser'] = NULL;
}

function _tzuser_show_entry(&$account) {
  if (!empty($account->tzuser['fullname'])) {
    $account->content['fullname'] = array(
      '#type' => 'user_profile_item',
      '#title' => t('Full name'),
      '#value' => $account->tzuser['fullname'],
      '#weight' => -10,
    );
  }
  if (!empty($account->tzuser['mobile'])) {
    $account->content['mobile'] = array(
      '#type' => 'user_profile_item',
      '#title' => t('Mobile number'),
      '#value' => $account->tzuser['mobile'],
      '#weight' => -9,
    );
  }
}

function _tzuser_validate_entry($edit) {
  if(!isset($edit['tzuser'])) {
    return;
  }

  $mobile = tzuser_validate_phone_number($edit['tzuser']['mobile']);
  if(empty($mobile)) {
    form_set_error('tzuser][mobile', t('Please enter a valid mobile number'));
  }
}

function _tzuser_user_form($account) {
  if($account->uid == 1) {
    // Don't add anything to the admin user
    return array();
  }

  $form['tzuser'] = array(
    '#tree' => TRUE,
    '#type' => 'fieldset',
    '#title' => t('TimeZynk Information'),
    '#weight' => -20,
  );
  $form['tzuser']['fullname'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Full name'),
    '#description' => t('The users full name'),
    '#default_value' => empty($account->tzuser['fullname']) ? '' : $account->tzuser['fullname'],
  );
  $form['tzuser']['mobile'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Mobile number'),
    '#description' => t('The users mobile number without country code'),
    '#default_value' => empty($account->tzuser['mobile']) ? '' : $account->tzuser['mobile'],
  );
  return $form;
}

function _tzuser_generate_fake_email() {
  return uniqid('user', TRUE) . '@' . $_SERVER['HTTP_HOST'];
}