define({
    root: {
        welcome_heading: 'Welcome to TimeZynk!',
        user_name_label: 'Username',
        password_label: 'Password',
        login_button: 'Login',
        button_send: 'Send',
        button_cancel: 'Cancel',
        button_delete: 'Delete',
        button_confirm: 'OK',
        failure: 'Failed',
        success: 'Success',
        companies_heading: 'Companies',
        companies_name_column: 'Name',
        companies_vat_column: 'VAT',
        companies_vat_label: 'VAT:',
        company_heading :'Company',
        edit_button: 'Edit',
        add_new_button: 'Add new',
        search_label: 'Search',
        modal_save_button: 'Save',
        modal_send_button: 'Send',
        modal_cancel_button: 'Cancel',
        modal_default_header: 'CHANGE HEADER',
        backend_label: 'Backend',
        backend_config_label: 'Config-ID',
        user_heading:'User',
        user_name_column: 'Full name',
        user_country_code: 'Country code',
        user_mobile_column: 'Mobile',
        user_last_login_column: 'Last login',
        user_first_login_column: 'First login',
        user_login_column: 'Login names',
        user_email_column: 'E-mail',
        user_username_label: 'Username',
        user_backend_column: 'Backend',
        user_last_login: "Last login",
        user_install_sms_checkbox: 'Install SMS',
        user_send_install_sms_checkbox: 'Resend install SMS',
        user_send_sms: 'Send sms',
        user_confirm_delete: "Are you sure that you wish to delete this user? This can't be undone",
        delete_successful : 'was successfully deleted.',
        sms_composer_header : 'Write message',
        message_sent : "Message successfully sent.",
        message_failed : "Failed to send message, please check the number",
        downloads_heading : "Downloads"
    },
    sv: true
});
