define({
    root: {
        button_send: 'Send',
        button_cancel: 'Cancel',
        button_delete: 'Delete',
        button_confirm: 'OK',
        failure: 'Failed',
        success: 'Success',
        search_label: 'Search',
        modal_send_button: 'Send',
        modal_cancel_button: 'Cancel',
        user_mobile_column: 'Mobile',
        user_email_column: 'E-mail',
        user_last_login: "Last login",
        user_send_sms: 'Send sms',
        user_booked: 'Booked',
        user_available : "Available",
        user_unavailable : "Unavailable",
        user_reported: 'Reported',
        sms_composer_header : 'Write message',
        message_sent : "Message successfully sent.",
        message_failed : "Failed to send message, please check the number",
        calendar_current_week: 'Current week',
        calendar_day: 'Day',
        calendar_week: 'Week',
    },
    sv: true
});
