<?php

define('TZINTELLITIME_MOCK_DELAY_MILLIS', variable_get('tzintellitime_mock_delay_millis', '0'));
define('TZINTELLITIME_MOCK_ENABLE_COMMENTS', variable_get('tzintellitime_mock_enable_comments', '1'));
define('TZINTELLITIME_MOCK_ERROR_CODE', variable_get('tzintellitime_mock_error_code', '200'));

/**
 * Implementation of hook_init
 * Disables caching for this page
 * @return unknown_type
 */
function tzintellitime_mock_init() {
  // We don't want caching for this module
  if (drupal_match_path($_GET['q'], 'demo/v2005/*')) {
    $GLOBALS['conf']['cache'] = FALSE;
  }
}

function tzintellitime_mock_menu() {
  $items['demo'] = array(
    'title' => 'Intellitime Demo',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tzintellitime_mock_presets'),
    'file' => 'tzintellitime_mock.presets.inc',
    'access callback' => TRUE,
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['demo/v2005'] = array(
    'title' => 'Intellitime Demo Login',
    'page callback' => 'tzintellitime_mock_request',
    'access callback' => TRUE,
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['admin/settings/tzintellitime_mock'] = array(
    'title' => 'Intellitime Mock',
    'description' => 'Settings for Intellitime Mockup site',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tzintellitime_mock_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'tzintellitime_mock.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function tzintellitime_mock_admin_settings_block() {
  return theme('admin_block_content', system_admin_menu_block(menu_get_item()));
}

function tzintellitime_mock_theme() {
  return array(
    'mock_timereport_page' => array(
      'arguments' => array(),
      'template' => 'mock_timereport_page',
    ),
    'mock_login_page' => array(
      'arguments' => array(),
      'template' => 'mock_login_page',
    ),
    'mock_user_table' => array(
      'arguments' => array(),
    ),
    'mock_assignments_table' => array(
      'arguments' => array(),
    ),
    'page' => array(
      'arguments' => array('content' => NULL, 'show_blocks' => TRUE, 'show_messages' => TRUE),
      'template' => 'page-demo',
     ),
  );
}

function tzintellitime_mock_timereports_render() {
  print theme('mock_timereport_page');
  exit();
}

function tzintellitime_mock_preprocess_mock_timereport_page(&$variables) {
  $mock_user = tzintellitime_mock_load_user($_SESSION['tzintellitime_mock_user_id']);

  $date = NULL;
  if (empty($_GET['DateInWeek'])) {
    $date = date_make_date('now');
    $date->setTime(12,0,0);
  } else {
    $date = date_make_date($_GET['DateInWeek'] . ' 12:00:00');
  }

  $variables['mock_user'] = $mock_user;
  $variables['comments'] = TZINTELLITIME_MOCK_ENABLE_COMMENTS;

  $all_reports = tzintellitime_mock_get_reports($mock_user);
  usort($all_reports, 'tzintellitime_mock_compare_reports');
  $reports = array();
  $unfinished_weeks = array();
  $total_duration = 0;
  // array to match ctl-ids with report-ids. the position matches the ctl number (ctlmapping[0] is ctl0 and so on)
  $ctlmapping = array();
  $all_reports_done = TRUE;
  foreach($all_reports as $report) {
    if(!$date) {
      if($report->state <= TZIntellitimeReport::STATE_OPEN) {
        $date = clone $report->get_begintime();
      } else {
        continue;
      }
    }
    $reportweek = $report->get_begintime()->format('o\WW');
    $dateweek = $date->format('o\WW');

    if($report->state <= TZIntellitimeReport::STATE_OPEN) {
      $unfinished_weeks[$reportweek] = $report->get_begintime()->format('Y-m-d');
    }

    if($dateweek == $reportweek) {
      if($report->state == TZIntellitimeReport::STATE_OPEN) {
        $all_reports_done = FALSE;
      }
      $begintime = $report->get_begintime();
      $endtime = $report->get_endtime();
      if($endtime < $begintime) {
        $endtime->modify('+1 day');
      }
      $duration = $endtime->format('U') - $begintime->format('U') - $report->break_duration_minutes*60;
      $total_duration += $duration;
      $report->duration_hours = round($duration/3600, 2);
      $reports[] = $report;
      $ctlmapping[] = $report->id;
    }
  }
  $serializedreportids = serialize($ctlmapping);
  $variables['ctlmap'] = base64_encode($serializedreportids);
  $variables['all_reports_done'] = $all_reports_done;

  if(!$date) {
    // If date is still null we have no reports, default to this week
    $date = tzbase_make_date();
  }

  $variables['reports'] = $reports;
  $variables['unfinished_weeks'] = $unfinished_weeks;
  $variables['total_duration_hours'] = round($total_duration/3600,2);

  $all_assignments = tzintellitime_mock_get_assignments();
  $assignments = array();
  $absence_codes = array();
  foreach($all_assignments as $assignment) {
    if(TZIntellitimeAssignment::TYPE_ASSIGNMENT == $assignment->type) {
      $assignments[] = $assignment;
    } else {
      $absence_codes[] = $assignment;
    }
  }

  $variables['assignments'] = $assignments;
  $variables['absence_codes'] = $absence_codes;

  $variables['current_week'] = $date->format('W');
  $variables['DateInWeek'] = $date->format('Y-m-d');

  // Move to monday if necessary
  if($date->format('N') != '1') {
    $date->modify('monday');
    $date->modify('-1 week');
  }

  // Check if week is in the future
  $variables['future'] = ($date > tzbase_make_date());

  // Build array of all dates this week
  $daysthisweek = array();
  for($i = 0; $i < 7; $i++) {
    $daysthisweek[] = clone $date;
    $date->modify('+1 day');
  }
  $variables['daysthisweek'] = $daysthisweek;

  $date->modify('-2 weeks');
  $variables['previous_dateinweek'] = $date->format('Y-m-d');
  $date->modify('+2 weeks');
  $variables['next_dateinweek'] = $date->format('Y-m-d');
}

function tzintellitime_mock_compare_reports($first, $second) {
  return $first->get_begintime()->format('U') - $second->get_begintime()->format('U');
}

function tzintellitime_mock_request() {
  $path = arg();

  $path = _tzintellitime_mock_rewrite_path($path);

  $filename = end($path);

  if(_tzintellitime_mock_serve_static($filename)) {
    exit();
  }

  if(TZINTELLITIME_MOCK_ERROR_CODE !== '200') {
    drupal_set_header('HTTP/1.1 ' . TZINTELLITIME_MOCK_ERROR_CODE . ' Error');
    print('Error: ' . TZINTELLITIME_MOCK_ERROR_CODE);
    exit();
  }

  switch(end($path)) {
    case 'Login.aspx':
      _tzintellitime_mock_login($path);
      break;

    case 'TimeReport.aspx':
      _tzintellitime_mock_verify_login();
      _tzintellitime_mock_timereports();
      break;

    case 'ReSync.aspx':
      _tzintellitime_mock_resync();
      break;

    case 'LogOut.aspx':
      _tzintellitime_mock_logout();
      drupal_goto('demo/v2005');
      break;

    default:
      drupal_not_found();
      break;
  }
}

function _tzintellitime_mock_login($path) {
  if('POST' === $_SERVER['REQUEST_METHOD']) {
    if(tzintellitime_mock_authenticate($_POST['TextBoxUserName'], $_POST['TextBoxPassword'])) {
      array_splice($path, -2, 2, array('TimeReport', 'TimeReport.aspx'));
      drupal_goto(implode('/', $path));
    } else {
      drupal_goto('demo/v2005');
    }
  } else {
    print theme('mock_login_page');
  }
}

function _tzintellitime_mock_timereports() {
  if(TZINTELLITIME_MOCK_DELAY_MILLIS && ctype_digit(TZINTELLITIME_MOCK_DELAY_MILLIS)) {
    usleep(TZINTELLITIME_MOCK_DELAY_MILLIS * 1000);
  }
  if('POST' === $_SERVER['REQUEST_METHOD']) {
    _tzintellitime_mock_timereports_post($_POST);
  }
  tzintellitime_mock_timereports_render();
}

function _tzintellitime_mock_timereports_post($post) {
  if(!empty($post['AddDateDropDown']) || !empty($post['AddRowDropDown'])) {
    _tzintellitime_mock_create_new_report($post);
  }

  $ctlid_reportid_map = _tzintellitime_mock_unpack_ctlid_map($post);
  foreach($ctlid_reportid_map as $ctlid => $reportid) {
    tzintellitime_mock_update_report($post, $ctlid, $reportid);
  }
}

function _tzintellitime_mock_unpack_ctlid_map($post) {
  return unserialize(base64_decode($post['__VIEWSTATE']));
}

function _tzintellitime_mock_rewrite_path($path) {
  if($path == array('demo', 'v2005')) {
    $path[] = 'Portal';
    $path[] = 'Login.aspx';
    drupal_goto(implode('/', $path));
  }

  if(count($path) < 3 && FALSE !== strpos(end($path), '.aspx')) {
    array_splice($path, -1, 0, 'Portal');
    drupal_goto(implode('/', $path));
  }
  return $path;
}

function _tzintellitime_mock_resync() {
  if (empty($_SESSION['tzintellitime_mock_user_id'])) {
    _tzintellitime_mock_logout();
    drupal_goto('demo/v2005');
  }

  $mock_user = tzintellitime_mock_load_user($_SESSION['tzintellitime_mock_user_id']);

  // Trigger sync
  if (module_exists('tzintellitime_sync')) {
    $account = user_load(array('name' => $mock_user->login));
    if ($account) {
      tzintellitime_sync_schedule_user($account->uid, TRUE);
    }
  }

  $query = array();
  if(!empty($_GET['DateInWeek'])) {
    $query['DateInWeek'] = $_GET['DateInWeek'];
  }
  drupal_goto('demo/v2005/TimeReport/TimeReport.aspx', $query);
}

function _tzintellitime_mock_verify_login() {
  if(!tzintellitime_mock_check_cookie()) {
    drupal_goto('demo/v2005/Portal/Login.aspx');
    exit();
  }
}

function _tzintellitime_mock_serve_static($filename) {
  $basedir = dirname(__FILE__);
  $filename = strtolower($filename);
  $expires = tzbase_make_date();
  $expires->modify('+10 years');

  // Check for static files
  $dirs = array('images', 'style');
  foreach($dirs as $dir) {
    $path = "$basedir/$dir/$filename";
    if(file_exists($path)) {
      $mime_type = file_get_mimetype($path);
      if(!empty($mime_type)) {
        drupal_set_header('Content-Type: ' . $mime_type);
      }
      drupal_set_header('Expires: ' . $expires->format('r'));
      drupal_set_header('Cache-Control: store, public');
      readfile($path);
      return TRUE;
    }
  }

  return FALSE;
}

function tzintellitime_mock_update_report($post, $ctlid, $reportid) {
  // query to get the report and create a report with information that we cannot from $post
  if(!empty($post['OldRowsRepeater:_ctl' . $ctlid . ':CheckBoxDelete'])) {
    _tzintellitime_mock_delete_report($reportid);
    return;
  }

  $report = tzintellitime_mock_load_object($reportid);
  if(!($report instanceof TZIntellitimeReport)) {
    return;
  }

  $report->state = _tzintellitime_mock_check_state($post, $ctlid);

  $prefix = 'OldRowsRepeater:_ctl' . $ctlid;
  if(isset($post["$prefix:TextboxTimeFrom"])) {
    $report->begin = _tzintellitime_mock_parse_time($post["$prefix:TextboxTimeFrom"]);
  }

  if(isset($post["$prefix:TextboxTimeTo"])) {
    $report->end = _tzintellitime_mock_parse_time($post["$prefix:TextboxTimeTo"]);
  }

  if(isset($post["$prefix:TextboxBreak"])) {
    $report->break_duration_minutes = _tzintellitime_mock_parse_duration($post["$prefix:TextboxBreak"]);
  }

  if(isset($post["$prefix:TextboxNote"])) {
    $report->comment = $post["$prefix:TextboxNote"];
  }
  tzintellitime_mock_store_object($report);
}

function _tzintellitime_mock_delete_report($reportid) {
  db_query('DELETE FROM {tzintellitime_mock_data} WHERE id=%d', $reportid);
}

function _tzintellitime_mock_check_state($post, $ctlid) {
  $state = TZIntellitimeReport::STATE_OPEN;
  if (!empty($post['DoneButton'])) {
    $state = TZIntellitimeReport::STATE_REPORTED;
  } else if (!empty($post['ChangeButton'])) {
    $state = TZIntellitimeReport::STATE_OPEN;
  } else if (!empty($post['OldRowsRepeater:_ctl' . $ctlid . ':CheckboxDayDone'])) {
    $state = TZIntellitimeReport::STATE_REPORTED;
  }
  return $state;
}

function _tzintellitime_mock_parse_time($time) {
  if (preg_match('/^([012]?\d{1}):?(\d{1,2})?/', $time, $match)) {
    $hours = intval($match[1], 10);
    $hours = min(23, $hours);
    $minutes = isset($match[2]) ? intval($match[2], 10) : 0;
    $minutes = min(59, $minutes);
    return sprintf('%02d:%02d', $hours, $minutes);
  }
  return '00:00';
}

function _tzintellitime_mock_parse_duration($duration) {
  $result = 0;
  if (preg_match('/\d+/', $duration, $match)) {
    $result = intval($match[0], 10);
  }
  return $result;
}

function tzintellitime_mock_authenticate($user, $pass) {
  $mock_user = tzintellitime_mock_load_user_by_name($user);
  if(!empty($mock_user) && $mock_user->password === $pass) {
    $token = md5($user . microtime() . $pass);
    $_SESSION['tzintellitime_mock_cookie'] = $token;
    $_SESSION['tzintellitime_mock_user_id'] = $mock_user->user_id;
    // Set a session cookie specific for the mock.
    setcookie('tzintellitime_mock_cookie', $token, time() + 1800, '/demo/v2005');
    return TRUE;
  }
  return FALSE;
}

/**
 * creates a TZIntellitimeReport object and saves it to our database.
 */
function _tzintellitime_mock_create_new_report($post) {
  if (empty($post['AddTimeFromTextBox']) ||
      empty($post['AddTimeToTextBox'])) {
    return;
  }

  // Break out year, month and day from the date object.
  list($year, $month, $day) = explode('-', $post['AddDateDropDown']);

  $report = new TZIntellitimeReport();
  $report->user_id = $_SESSION['tzintellitime_mock_user_id'];
  $report->year = intval($year, 10);
  $report->month = intval($month, 10);
  $report->day = intval($day, 10);
  $report->begin = _tzintellitime_mock_parse_time($post['AddTimeFromTextBox']);
  $report->end = _tzintellitime_mock_parse_time($post['AddTimeToTextBox']);
  $report->break_duration_minutes = _tzintellitime_mock_parse_duration($post['AddBreakTextBox']);

  // check if commentfield is activated
  if(!empty($post['AddNoteTextBox'])) {
    $report->comment = $post['AddNoteTextBox'];
  }
  if(!empty($post['AddRowDropDown'])) {
    $assignment = tzintellitime_mock_load_object($post['AddRowDropDown']);
    if(!empty($assignment) && $assignment instanceof TZIntellitimeAssignment) {
      $report->title = $assignment->title;
      $report->assignment_id = $assignment->id;
    } else {
      return;
    }
  }

  // Create and save report
  tzintellitime_mock_store_object($report);
}


function tzintellitime_mock_check_cookie() {
  if(!empty($_SESSION['tzintellitime_mock_cookie']) && !empty($_COOKIE['tzintellitime_mock_cookie']) &&
      $_SESSION['tzintellitime_mock_cookie'] == $_COOKIE['tzintellitime_mock_cookie']) {
    // Check that user_id exists
    $mock_user = tzintellitime_mock_load_user($_SESSION['tzintellitime_mock_user_id']);
    if(!empty($mock_user) && !empty($mock_user->login)) {
      // Set a session cookie specific for the mock.
      setcookie('tzintellitime_mock_cookie', $_SESSION['tzintellitime_mock_cookie'], time() + 1800, '/demo/v2005');
      return TRUE;
    }
  }
  _tzintellitime_mock_logout();
  return FALSE;
}

function _tzintellitime_mock_logout() {
  // Unset both session and cookie
  unset($_SESSION['tzintellitime_mock_cookie']);
  unset($_SESSION['tzintellitime_mock_user_id']);
  setcookie('tzintellitime_mock_cookie', '', time() - 3600, '/demo/v2005');
}


function tzintellitime_mock_get_reports($mock_user=NULL) {

  // Build SQL query
  $query = 'SELECT * FROM {tzintellitime_mock_data}';
  $query_args = array();
  if(!empty($mock_user)) {
    $query .= ' WHERE user_id = %d';
    $query_args[] = $mock_user->user_id;
  }
  $query .= ' ORDER BY id ASC';

  $reports = array();
  $result = db_query($query, $query_args);
  while($row = db_fetch_object($result)) {
    $object = unserialize($row->data);
    if($object instanceof TZIntellitimeReport) {
      $reports[] = _tzintellitime_mock_fill_id($object, $row);
    }
  }
  return $reports;
}

function tzintellitime_mock_get_assignments() {
  $assignments = array();

  $result = db_query('SELECT * FROM {tzintellitime_mock_data} WHERE user_id = 0 ORDER BY id ASC');
  while($row = db_fetch_object($result)) {
    $object = unserialize($row->data);
    if($object instanceof TZIntellitimeAssignment) {
      $assignments[] = _tzintellitime_mock_fill_id($object, $row);
    }
  }

  return $assignments;
}

function tzintellitime_mock_get_users() {
  $users = array();
  $result = db_query('SELECT * FROM {tzintellitime_mock_users}');
  while ($row = db_fetch_object($result)) {
    $users[] = $row;
  }
  return $users;
}

function _tzintellitime_mock_fill_id(&$object, $row) {
  if($object) {
    $object->user_id = $row->user_id;
    $object->id = $row->id;
  }
  return $object;
}

function tzintellitime_mock_load_user($user_id) {
  return db_fetch_object(db_query('SELECT * FROM {tzintellitime_mock_users} WHERE user_id = %d', $user_id));
}

function tzintellitime_mock_load_user_by_name($user_name) {
  return db_fetch_object(db_query('SELECT * FROM {tzintellitime_mock_users} WHERE LOWER(login) = \'%s\'', strtolower($user_name)));
}

function tzintellitime_mock_store_object($object) {
  $db_object = array(
    'user_id' => 0,
    'data' => serialize($object),
  );

  if(!empty($object->user_id)) {
    $db_object['user_id'] = $object->user_id;
  }

  if(!empty($object->id)) {
    // Existing ID, update instead
    $db_object['id'] = $object->id;
    drupal_write_record('tzintellitime_mock_data', $db_object, 'id');
  } else {
    drupal_write_record('tzintellitime_mock_data', $db_object);
  }

  return $db_object['id'];
}

function tzintellitime_mock_load_object($id) {
  $result = db_query('SELECT * FROM {tzintellitime_mock_data} WHERE id = %d', $id);
  $row = db_fetch_object($result);
  $obj = unserialize($row->data);
  return _tzintellitime_mock_fill_id($obj, $row);
}

function tzintellitime_mock_schedule_all_users() {
  $old_delay = TZINTELLITIME_MOCK_DELAY_MILLIS;
  variable_set('tzintellitime_mock_delay_millis', 0);

  $result = db_query('SELECT * FROM {tzintellitime_mock_users}');
  while($mock_user = db_fetch_object($result)) {
    tzintellitime_mock_schedule_user($mock_user);
  }

  variable_set('tzintellitime_mock_delay_millis', $old_delay);
}

function tzintellitime_mock_schedule_user($mock_user) {
  if (is_numeric($mock_user)) {
    $mock_user = tzintellitime_mock_load_user($mock_user);
  }
  if (!$mock_user) {
    return FALSE;
  }

  $account = user_load(array('name' => $mock_user->login, 'status' => 1));
  try {
    $account = tzintellitime_server_auth($account, $mock_user->login, $mock_user->password);
  } catch (Exception $e) {}
  if(!$account) {
    return FALSE;
  }
  tzintellitime_sync_schedule_user($account->uid);
  return TRUE;
}