<?php
/**
 * Service for exporting time reports from TimeZynk as excel files.
 */

/**
 * Implementation of hook_menu().
 */
function excelexport_menu() {
  $items = array();
  $items['timereports/xls'] = array(
    'title' => 'To Excel',
    'page callback' => 'excelexport_export',
    'access arguments' => array('export timereports to excel'),
    'file' => 'excelexport.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 20,
  );
  return $items;
}

function excelexport_perm() {
  return array('export timereports to excel');
}