<?php
/**
 * Service for exporting time reports from TimeZynk as excel files.
 */

/**
 * Implementation of hook_help().
 */
function excelexport_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description':
      return t('Provides excel export functionality for time reports. Requires tzbase.module.');
  }
}

/**
 * Implementation of hook_menu().
 */
function excelexport_menu() {
	$items = array();
	$items['export/xls'] = array(
		'title' => 'Export time reports to excel',
		'page callback' => 'excelexport_export',
		'access arguments' => array('edit any tzreport content'),
		'file' => 'excelexport.inc',
		'type' => MENU_SUGGESTED_ITEM,
		);
	return $items;

}