<?php

function tzintellitime_mock_menu() {
  $items['IntelliplanWeb'] = array(
    'title' => 'Intellitime Mockup',
    'page callback' => 'tzintellitime_mock_request',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function tzintellitime_mock_request() {
  $valid_users = array(
    'test user' => md5('test password'),
  );
  $path = arg();
  watchdog('mock', 'Request for path ' . print_r($path, TRUE));
  if(count($path) < 3 && FALSE !== strpos(end($path), '.aspx')) {
    array_splice($path, -1, 0, 'Portal');
    drupal_goto(implode('/', $path));
  }
  switch(end($path)) {
    case 'Login.aspx':
      if('POST' === $_SERVER['REQUEST_METHOD']) {
        // Check login
        $user = $_POST['TextBoxUserName'];
        $pass = md5($_POST['TextBoxPassword']);
        if(empty($valid_users[$user]) || $valid_users[$user] !== $pass) {
          drupal_goto('IntelliplanWeb/Portal/Login.aspx');
        } else {
          $value = md5($path . microtime());
          variable_set('tzintellitime_mock_cookie', $value);
          // Set a session cookie specific for the mock.
          setcookie('tzintellitime_mock_cookie', $value, 0, '/IntelliplanWeb');
          array_pop($path);
          $path[] = 'Main.aspx';
          drupal_goto(implode('/', $path));
        }
      } else {
        readfile(dirname(__FILE__) . '/intellitime-login-page.html');
      }
      break;

    case 'Main.aspx':
      if (tzintellitime_mock_check_cookie()) {
        readfile(dirname(__FILE__) . '/intellitime-main-page.html');
      } else {
        drupal_goto('IntelliplanWeb/Portal/Login.aspx');
      }
      break;

    case 'TimeReport.aspx':
      if (tzintellitime_mock_check_cookie()) {
        readfile(dirname(__FILE__) . '/intellitime-timereport-page.html');
      } else {
        drupal_goto('IntelliplanWeb/Portal/Login.aspx');
      }
      break;

    case 'LogOut.aspx':
      variable_del('tzintellitime_mock_cookie');
      drupal_goto('IntelliplanWeb/Portal/Login.aspx');
      break;

    default:
      drupal_goto('IntelliplanWeb/Portal/Login.aspx');
      break;
  }
}
function tzintellitime_mock_check_cookie() {
    return (variable_get('tzintellitime_mock_cookie', 'wrong cookie') == $_COOKIE['tzintellitime_mock_cookie']);
  }