define({

        button_send: 'Skicka',
        button_cancel: 'Avbryt',
        button_delete: 'Ta bort',
        button_confirm: 'OK',
        failure: 'Misslyckades',
        success: 'Lyckades',
        search_label: 'Sök',
        modal_send_button: 'Spara',
        modal_cancel_button: 'Avbryt',
        user_mobile_column: 'Mobil',
        user_email_column: 'E-post',
        user_last_login: "Senaste inloggning",
        user_send_sms: 'Skicka SMS',
        user_booked: 'Bokad',
        user_available : "Tillgänglig",
        user_unavailable : "Ej tillgänglig",
        user_reported: 'Rapporterad',
        sms_composer_header : 'Skriv meddelande',
        message_sent : "Meddelandet har skickats.",
        message_failed : "Kunde inte skicka meddelandet.",
        calendar_current_week: 'Nuvarande vecka',
        calendar_day: 'Dag',
        calendar_week: 'Vecka',
});
