<?php

/**
 * Definition of hook_menu()
 */
function tzsms_ui_menu() {
  $items['tzsms'] = array(
    'title' => 'SMS',
    'access arguments' => array('send sms'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tzsms_ui_send_sms_form'),
    'file' => 'tzsms_ui.send.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['tzsms/text'] = array(
    'title' => 'Send',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('send sms'),
    'weight' => -10,
  );
  return $items;
}

/**
 * Implementation of hook_perm()
 * Define available permissions.
 */
function tzsms_ui_perm() {
  return array('send sms');
}

function tzsms_ui_list_users() {
  $query = db_query('SELECT uid FROM {users} WHERE status = 1 AND uid != 0');
  $users = array();
  while($uid = db_result($query)) {
    $account = user_load($uid);
    if(empty($account->tzuser['mobile'])) {
      continue;
    }
    if(FALSE === tzuser_validate_phone_number($account->tzuser['mobile'])) {
      continue;
    }
    $users[] = $account;
  }
  return $users;
}

function tzsms_ui_recipient_form($default_policy = 'include', $default_selection = array()) {
  $form = array(
    '#tree' => TRUE,
    '#type' => 'fieldset',
    '#title' => t('Recipients'),
    '#collapsible' => FALSE,
  );

  $form['policy'] = array(
    '#type' => 'radios',
    '#title' => t('Select recipients'),
    '#options' => array(
      'include' => t('Send ONLY to the users marked below'),
      'exclude' => t('Send to EVERYONE, except the users marked below'),
    ),
    '#default_value' => $default_policy,
  );

  $accounts = tzsms_ui_list_users();
  $userlist = array();
  foreach($accounts as $account) {
    $userlist[$account->uid] = check_plain($account->tzuser['fullname']);
  }
  asort($userlist);

  $form['users'] = array(
    '#type' => 'select',
    '#options' => $userlist,
    '#multiple' => TRUE,
    '#size' => 10,
    '#default_value' => $default_selection,
  );

  return $form;
}