<?php
/**
 * @file Provide SMS services for TimeZynk
 */

/**
 * Implements hook_user_operations. Adds a new selection to the mass user action
 * dropdown at the administration pages.
 */
function tzsms_user_operations() {
  $operations['tzsms_reset_pw_and_send_install_sms'] = array(
    'label' => t('Reset password and send new TimeZynk installation SMS'),
    'callback' => 'tzsms_reset_pw_and_send_install_sms',
  );
  $operations['tzsms_send_install_sms'] = array(
    'label' => t('Send new TimeZynk installation SMS'),
    'callback' => 'tzsms_send_install_sms',
  );
  return $operations;
}

/**
 * Validate a mobile phone number and strip out all extra characters
 * @param string $number phone number to validate
 * @return all-numeric phone number if success, otherwise FALSE
 */
function tzsms_validate_phone_number($number) {
  // Remove characters like '+', '-', ' ' and '/'
  $mobile_number = preg_replace('/[\+\- \/]/', '', $number);
  // There should be only digits left now
  if(!ctype_digit($mobile_number) || strlen($mobile_number) < 6) {
    return FALSE;
  }
  return $mobile_number;
}


/**
 * Provide a simple form to set the default country code
 * @ingroup forms
 * @see system_settings_form()
 */
function tzsms_form_user_admin_settings_alter(&$form, &$form_state) {
  $form['tzsms_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('TimeZynk SMS settings'),
    '#description' => t('TimeZynk sends out installation instructions via SMS, configure the settings here!'),
    '#weight' => 0,
    'tzsms_default_country_code' => array(
      '#type' => 'textfield',
      '#title' => t('Default country code for this site'),
      '#default_value' => variable_get('tzsms_default_country_code', '46'),
      '#description' => t('The country code will be used to send installation SMS to the users registered on this site'),
    ),
    'tzsms_install_sms_template' => array(
      '#type' => 'textarea',
      '#title' => t('The content of the SMS'),
      '#default_value' => variable_get('tzsms_install_sms_template', tzsms_install_sms_template()),
      '#description' => t('The available variables are: !url, !username and !password'),
    ),
    'tzsms_install_sms_no_password_template' => array(
      '#type' => 'textarea',
      '#title' => t('The content of the SMS when keeping the same password'),
      '#default_value' => variable_get('tzsms_install_sms_no_password_template', tzsms_install_sms_no_password_template()),
      '#description' => t('The available variables are: !url and !username'),
    ),
  );
  $form['#validate'][] = 'tzsms_form_user_admin_settings_validate';
}


/**
 * Validate the form to check that admin has entered correct TimeZynk
 * SMS settings.
 * @param $form submitted form
 * @param $form_state submitted form state
 */
function tzsms_form_user_admin_settings_validate(&$form, &$form_state) {
  /* Country code must be all numeric and contain a maximum of 4 digits since
   * a couple of countries like Barbados and Jamaica have 4 digit country codes */
  $country_code = $form_state['values']['tzsms_default_country_code'];
  if(strlen($country_code) > 4 || !ctype_digit($country_code)) {
    form_set_error('tzsms_default_country_code', t('You must enter a numeric country code (e.g. 46 for Sweden)!'));
  }
}


/**
 * Hook into the user_register form and detect when it is submitted.
 * We do it this way, since it is the only place where the password
 * is still available in clear-text.
 *
 * @param $form form to alter
 * @param $form_state current form state
 */
function tzsms_form_user_register_alter(&$form, &$form_state) {
  // Add our own submit handler that sends the install sms
  $form['#submit'][] = 'tzsms_form_user_register_submit';
}


/**
 * Submit handler for user_register form.
 *
 * @param $form form that was posted
 * @param $form_state form state with current values
 */
function tzsms_form_user_register_submit($form, &$form_state) {
  $username = $form_state['values']['name'];
  $password = $form_state['values']['pass'];
  tzsms_send_new_user_sms($username, $username, $password);
}


/**
 * Alter the reset password form to send the new password over SMS instead
 */
function tzsms_form_user_pass_alter(&$form, &$form_state) {
  $form['name']['#title'] = t('Your mobile phone number or e-mail address');
  $form['submit']['#value'] = t('Send new password over SMS');
  $form['#submit'] = array('tzsms_form_user_pass_submit');
}

/**
 * Submit handler for reset password form
 */
function tzsms_form_user_pass_submit($form, &$form_state) {
  $account = $form_state['values']['account'];
  tzsms_reset_pw_and_send_install_sms(array($account->uid));
  watchdog('tzsms', 'User %name requested new password over SMS', array('%name' => $account->name));
  drupal_set_message(t('New password has been sent to you over SMS'));
  $form_state['redirect'] = 'user';
}

/**
 * Resets the password for the selected users and send new
 * installations sms messages.
 * @param $users array of user IDs
 */
function tzsms_reset_pw_and_send_install_sms($users) {
  foreach($users as $uid) {
    $user = user_load($uid);
    $new_pass = genpass_generate();
    $user = user_save($user, array('pass' => $new_pass));
    if($user) {
      tzsms_send_new_user_sms($user->name, $user->name, $new_pass);
    }
  }
}

/**
 * Function send an installation SMS to the selected users
 */
function tzsms_send_install_sms($users) {
  foreach($users as $uid) {
    $user = user_load($uid);
    if($user) {
      tzsms_send_new_user_sms($user->name, $user->name);
    }
  }
}

/**
 * Sends an installation sms to the user that is registered by using
 * the user_register form.
 *
 * @param $phonenbr phone number to send SMS to
 * @param $password password to send
 */
function tzsms_send_new_user_sms($username, $phonenbr, $password = NULL) {
  watchdog('tzsms', 'Sending install SMS to !nbr', array('!nbr' => $phonenbr));
  $country_code = intval(variable_get('tzsms_default_country_code', '46'));
  $msg = '';
  if($password) {
    $msg = tzsms_install_sms_template(array(
    	'!url' => url('tz.jad',  array('absolute' => TRUE)),
    	'!username' => $phonenbr,
    	'!password' => $password)
    );
  } else {
    $msg = tzsms_install_sms_no_password_template(array(
    	'!url' => url('tz.jad',  array('absolute' => TRUE)),
    	'!username' => $phonenbr)
    );
  }
  sms_send($phonenbr, $msg, array('country' => $country_code));
}

/**
 * Generate install sms message from template
 * @param $variables array with substitution variables (!url, !username, !password)
 */
function tzsms_install_sms_template($variables = array()) {
  if ($admin_setting = variable_get('tzsms_install_sms_template', FALSE)) {
    // An admin setting overrides the default string.
    return strtr($admin_setting, $variables);
  } else {
    return t('Welcome to TimeZynk! Visit !url to install, then login using !username as username and "!password" as password.',
      $variables);
  }
}

/**
 * Generate install sms message from template
 * @param $variables array with substitution variables (!url, !username, !password)
 */
function tzsms_install_sms_no_password_template($variables = array()) {
  if ($admin_setting = variable_get('tzsms_install_sms_no_password_template', FALSE)) {
    // An admin setting overrides the default string.
    return strtr($admin_setting, $variables);
  } else {
    return t('Welcome to TimeZynk! Visit !url to install, then login using !username as username.',
      $variables);
  }
}
