<?php
/**
 * @file Provide SMS services for TimeZynk
 */

/**
 * SMS type definition for standard user SMS messages
 */
define('TZSMS_TYPE_USER_SMS', 0);

/**
 * SMS type definition for installation SMS messages
 */
define('TZSMS_TYPE_INSTALL_SMS', 1);

/**
 * SMS type definition for automatic reminder SMS messages
 */
define('TZSMS_TYPE_AUTO_REMINDER_SMS', 2);

define('TZSMS_DEFAULT_COUNTRY_CODE', variable_get('tzsms_default_country_code', '46'));
define('TZSMS_DEFAULT_SENDER', variable_get('tzsms_default_sender', 'TimeZynk'));
define('TZSMS_BACKEND', variable_get('tzsms_backend', 'beepsend'));

define('TZSMS_BEEPSEND_USERNAME', 'TimeZynk01');
define('TZSMS_BEEPSEND_PASSWORD', 'HanUzEg');


function tzsms_menu() {
  $items = array();
  $items['admin/settings/timezynk/tzsms'] = array(
    'title' => 'SMS',
    'description' => 'Sitewide settings for SMS.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tzsms_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/tzsms.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_user_operations. Adds a new selection to the mass user action
 * dropdown at the administration pages.
 */
function tzsms_user_operations() {
  $operations['tzsms_reset_pw_and_send_install_sms'] = array(
    'label' => t('Reset password and send new TimeZynk installation SMS'),
    'callback' => 'tzsms_reset_pw_and_send_install_sms',
  );
  $operations['tzsms_send_install_sms'] = array(
    'label' => t('Send new TimeZynk installation SMS'),
    'callback' => 'tzsms_send_install_sms',
  );
  return $operations;
}

/**
 * Send a SMS message to phonenbr. This is the lowest level function you
 * should call to send a SMS. Do not use the SMS Framework module
 * directly since it would bypass the statistics functions.
 *
 * @param int $type SMS type ID, e.g. TZSMS_TYPE_USER_SMS
 * @param string $phonenbr Phone number to send to
 * @param string $msg message to send
 */
function tzsms_send($type, $phonenbr, $msg) {
  $valid_number = tzuser_validate_phone_number($phonenbr);
  if(FALSE === $valid_number) {
    watchdog('tzsms', 'Failed to send SMS to invalid number: @number', array('@number' => $phonenbr));
    return FALSE;
  }

  // Invoke tzsms_send hook to allow modules to collect statistics or billing info
  module_invoke_all('tzsms_send', $type, $valid_number, mb_strlen($msg));

  // Load country code
  $international_number = tzsms_set_country_code($valid_number, TZSMS_DEFAULT_COUNTRY_CODE);

  $factory = new SmsBackendFactory(TZSMS_BACKEND);
  $backend = $factory->create();

  $message_id = '';
  try {
    $message_id = $backend->send(TZSMS_DEFAULT_SENDER, $international_number, $msg);
  } catch (SmsBackendException $e) {
    watchdog('tzsms', 'Failed to send SMS message: @error', array('@error' => $e->getMessage()));
  }

  watchdog('tzsms', 'Message successfully sent with id: "@id"', array('@id' => $message_id));

  return TRUE;
}

function tzsms_set_country_code($number, $country_code) {
  return preg_replace('/^0+/', $country_code, $number);
}

function tzsms_tzuser_add_user_notify($account, $password = '') {
  tzsms_send_new_user_sms(
      $account->tzuser['mobile'],
      $account->name,
      $password
  );
}


/**
 * Hook into the user_register form and detect when it is submitted.
 * We do it this way, since it is the only place where the password
 * is still available in clear-text.
 *
 * @param $form form to alter
 * @param $form_state current form state
 */
function tzsms_form_user_register_alter(&$form, &$form_state) {
  // Add our own submit handler that sends the install sms
  $form['#submit'][] = 'tzsms_form_user_register_submit';
}


/**
 * Submit handler for user_register form.
 *
 * @param $form form that was posted
 * @param $form_state form state with current values
 */
function tzsms_form_user_register_submit($form, &$form_state) {
  $mobile = $form_state['values']['tzuser']['mobile'];
  $username = $form_state['values']['name'];
  $password = $form_state['values']['pass'];
  tzsms_send_new_user_sms($mobile, $username, $password);
}


/**
 * Alter the reset password form to send the new password over SMS instead
 */
function tzsms_form_user_pass_alter(&$form, &$form_state) {
  $form['name']['#title'] = t('Your mobile phone number or e-mail address');
  $form['submit']['#value'] = t('Send new password over SMS');
  $form['#submit'] = array('tzsms_form_user_pass_submit');
}

/**
 * Submit handler for reset password form
 */
function tzsms_form_user_pass_submit($form, &$form_state) {
  $account = $form_state['values']['account'];
  tzsms_reset_pw_and_send_install_sms(array($account->uid));
  watchdog('tzsms', 'Requested new password over SMS', array(), WATCHDOG_NOTICE, theme('username', $account));
  drupal_set_message(t('New password has been sent to you over SMS'));
  $form_state['redirect'] = 'user';
}

/**
 * Resets the password for the selected users and send new
 * installations sms messages.
 * @param $users array of user IDs
 */
function tzsms_reset_pw_and_send_install_sms($users) {
  foreach($users as $uid) {
    $user = user_load($uid);
    $new_pass = genpass_generate();
    $user = user_save($user, array('pass' => $new_pass));
    if($user) {
      tzsms_send_new_user_sms($user->tzuser['mobile'], $user->name, $new_pass);
    }
  }
}

/**
 * Function send an installation SMS to the selected users
 */
function tzsms_send_install_sms($users) {
  foreach($users as $uid) {
    $user = user_load($uid);
    if($user) {
      tzsms_send_new_user_sms($user->tzuser['mobile'], $user->name);
    }
  }
}

/**
 * Sends an installation sms to the user that is registered by using
 * the user_register form.
 *
 * @param $phonenbr phone number to send SMS to
 * @param $username username to substitute in the install SMS template
 * @param $password password to substitute in the install SMS template
 */
function tzsms_send_new_user_sms($phonenbr, $username, $password = NULL) {
  watchdog('tzsms', 'Sending install SMS to !nbr', array('!nbr' => $phonenbr));
  $msg = '';
  if($password) {
    $msg = tzsms_install_sms_template(array(
    	'!url' => url('tz.jad',  array('absolute' => TRUE)),
        '!username' => $username,
        '!password' => $password
      )
    );
  } else {
    $msg = tzsms_install_sms_no_password_template(array(
        '!url' => url('tz.jad',  array('absolute' => TRUE)),
        '!username' => $username
      )
    );
  }
  tzsms_send(TZSMS_TYPE_INSTALL_SMS, $phonenbr, $msg);
}

/**
 * Generate install sms message from template
 * @param $variables array with substitution variables (!url, !username, !password)
 */
function tzsms_install_sms_template($variables = array()) {
  if ($admin_setting = variable_get('tzsms_install_sms_template', FALSE)) {
    // An admin setting overrides the default string.
    return strtr($admin_setting, $variables);
  } else {
    return t('Welcome to TimeZynk! Visit !url to install, then login using "!username" as username and "!password" as password.',
      $variables);
  }
}

/**
 * Generate install sms message from template
 * @param $variables array with substitution variables (!url, !username, !password)
 */
function tzsms_install_sms_no_password_template($variables = array()) {
  if ($admin_setting = variable_get('tzsms_install_sms_no_password_template', FALSE)) {
    // An admin setting overrides the default string.
    return strtr($admin_setting, $variables);
  } else {
    return t('Welcome to TimeZynk! Visit !url to install, then login using "!username" as username.',
      $variables);
  }
}
