<?php

/**
 * Definition of hook_menu()
 */
function tzsms_ui_menu() {
  $items['tzsms'] = array(
    'title' => 'SMS',
    'access arguments' => array('send sms'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tzsms_ui_send_sms_form'),
    'file' => 'includes/tzsms_ui.send.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['tzsms/text'] = array(
    'title' => 'Send',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('send sms'),
    'weight' => -10,
  );
  $items['tzsms/install_sms_ajax'] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('send sms'),
    'page callback' => 'tzsms_ui_install_sms_ajax',
  );
  $items['api/sms'] = array(
    'type' => MENU_CALLBACK,
    'access callback' => 'tzapi_authorize',
    'access arguments' => array('send sms'),
    'page callback' => 'tzsms_ui_sms_api',
  );
  return $items;
}

/**
 * Implementation of hook_perm()
 * Define available permissions.
 */
function tzsms_ui_perm() {
  return array('send sms');
}

function tzsms_ui_list_users() {
  $query = db_query('SELECT uid FROM {users} WHERE status = 1 AND uid != 0');
  $users = array();
  while($uid = db_result($query)) {
    $account = user_load($uid);
    if(empty($account->tzuser['mobile'])) {
      continue;
    }
    if(!tzuser_validate_phone_number($account->tzuser['mobile'])) {
      continue;
    }
    $users[] = $account;
  }
  return $users;
}

function tzsms_ui_recipient_form($default_policy = 'include', $default_selection = array()) {
  $form = array(
    '#tree' => TRUE,
    '#type' => 'fieldset',
    '#title' => t('Recipients'),
    '#collapsible' => FALSE,
  );

  $form['policy'] = array(
    '#type' => 'radios',
    '#title' => t('Select recipients'),
    '#options' => array(
      'include' => t('Send ONLY to the users marked below'),
      'exclude' => t('Send to EVERYONE, except the users marked below'),
    ),
    '#default_value' => $default_policy,
  );

  $accounts = tzsms_ui_list_users();
  $userlist = array();
  foreach($accounts as $account) {
    $userlist[$account->uid] = check_plain($account->tzuser['fullname']);
  }
  asort($userlist);

  $form['users'] = array(
    '#type' => 'select',
    '#options' => $userlist,
    '#multiple' => TRUE,
    '#size' => 10,
    '#default_value' => $default_selection,
  );

  return $form;
}

function tzsms_ui_add_js() {
  tzbase_add_progress_js();
  drupal_add_js(drupal_get_path('module', 'tzsms_ui') . '/javascript/tzsms_ui.js');
  drupal_add_js(
    array('tzsms_ui' => array(
      'tzsms_reminder_sms_template' => tzsms_reminder_sms_template(),
    )),
    'setting'
  );
  drupal_add_js(drupal_get_path('module', 'tzsms_ui') . '/javascript/tzsms_ui.user.js');
}

function tzsms_ui_form_tzuser_user_overview_alter(&$form, &$form_state) {
  tzsms_ui_add_js();

  $form['send_reminder_sms'] = array(
    '#type' => 'submit',
    '#value' => t('Send reminder SMS'),
    '#access' => user_access('send sms'),
  );
  $form['send_install_sms'] = array(
    '#type' => 'submit',
    '#value' => t('New install SMS'),
    '#access' => user_access('send sms'),
  );
  $form['send_text_sms'] = array(
    '#type' => 'submit',
    '#value' => t('Send text-SMS'),
    '#access' => user_access('send sms'),
  );
}

function tzsms_ui_form_tzbase_availability_form_alter(&$form, &$form_state) {
  tzsms_ui_add_js();

  $form['send_text_sms'] = array(
    '#type' => 'submit',
    '#value' => t('Send text-SMS'),
    '#access' => user_access('send sms'),
  );
}

function tzsms_send_text_sms($users, $text) {
  $sms_count = 0;
  foreach ($users as $uid) {
    $account = user_load($uid);
    if (empty($account->tzuser['mobile'])) {
      continue;
    }
    tzsms_send(
      TZSMS_TYPE_USER_SMS,
      $account->tzuser['mobile'],
      $text
    );
    $sms_count++;
  }
  return $sms_count;
}

function tzsms_ui_install_sms_ajax() {
  if (empty($_POST['selected_users'])) {
    return;
  }

  $users = array_values($_POST['selected_users']);
  tzsms_send_install_sms($users);
  drupal_set_message(t('Sent @count SMS messages', array('@count' => count($users))));
  print theme('status_messages', 'status');
}

function tzsms_ui_sms_api() {
  $raw_data = file_get_contents('php://input');
  $req = json_decode($raw_data);

  if (empty($req->recipients) ||
      empty($req->text)) {
    return;
  }

  $sms_count = tzsms_send_text_sms(array_values($req->recipients),
                                   trim($req->text));

  drupal_set_header('Content-Type: application/json; charset=utf-8');
  print json_encode(array('sent' => intval($sms_count)));
}
