<?php
/**
 * Service for serving the TimeZynk mobile client
 */

/**
 * Implementation of hook_help().
 */
function timezynk_service_help($path, $arg) {
  switch ($path) {
    case 'admin/help#services_timezynk':
      return t('<p>Provides methods for communicating with TimeZynk mobile. Requires services.module.</p>');
    case 'admin/modules#description':
      return t('Provides methods for communicating with TimeZynk mobile. Requires services.module.');
  }
}

/**
 * Implementation of hook_service().
 */
function timezynk_service_service() {
  return array(
    // timezynk.login
    array(
      '#method'           => 'timezynk.login',
      '#callback'         => 'timezynk_service_login',
      '#file'             => array('file' => 'inc', 'module' => 'timezynk_service'),
      '#args'             => array(
        array(
          '#name'           => 'username',
          '#type'           => 'string',
          '#description'    => t('A valid username.'),
        ),
        array(
          '#name'           => 'password',
          '#type'           => 'string',
          '#description'    => t('A valid password.'),
        ),
      ),
      '#return'           => 'struct',
      '#help'             => t('Login and retreive user data.')
    ),
    
    // timezynk.get
    array(
      '#method'           => 'timezynk.get',
      '#callback'         => 'timezynk_service_get',
      '#file'             => array('file' => 'inc', 'module' => 'timezynk_service'),
      '#args'             => array(
        array(
          '#name'           => 'offset',
          '#type'           => 'int',
          '#description'    => t('Offset to start fetching from'),
        ),
        array(
          '#name'           => 'limit',
          '#type'           => 'int',
          '#description'    => t('Number of reports to fetch'),
        ),
      ),
      '#return'           => 'array',
      '#help'             => t('Retreive time reports')
    ),
  );
}